travis:
  secure:
    BINSTAR_TOKEN: rLcSbW3jl9bLRC/f8htyracG9k/PR0Xa1FDYqp8l1p0O9m1HTgE7RrOKiI/tINGd7Adn6fPSWrnwDYTFqH4kMQp+gU7LFNoFFjyTJcN+X5brIt08qn0K/5r5DL25pJQBOM+DxoFgUsOHiZPWwhJE8Wv6LwyrwLTGxEVIz+B9HmGXA6cwtwOQiQCzgL+GSWEZEuFwkm+XxiIVai57ycAJ6Qgs3FLKAaLAVMlVBUEoCFJUofcs8qJ6Qw8/7c89RdG5SyAOcxerV/nEKLAPRLIQRegrslfDTp0NPJWdWEv7KfIEwCv5L8kqZduDXUzveqdUACCiecF58FKr7Gv7m2N0S3GGXPBJ7Ht6WquQg3r0bzqrwVrVLhDxCcM7mu4UmkcbOzcvoNkfl5lqnBxjU+tx6R0Jer0HFbrpbUKDxECKZEbn5BUzm8IFT1SwYGAF3Ay08JI+akvizr781Q1smpR1eN+MO2lH5gAYPeDiTJ614e7QqSqdoT3Wov7NDDR2fDG1xHSLoUD3ypkS1CTHFy8lT4Ae8GuQLGcnDzEDnD4Y4xbM3ZF8B0N7E9u/SHFR40p8iyhHmAh/HF3Peu6xQLYhCsjx4pLk94JquxfOVXWpl7ckDRrmu6lF0ECtGxo8lZcNsNONH1T9IpuhFIhjo6jXbzkyduZlCJzmcQp0FT+csGg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
