travis:
  secure:
    BINSTAR_TOKEN: SG/FD6hMG/+e5hQrFdNDHP6S9vgb8OGup2n+ejFtTkdArManY0Vq+6Si9l/I0YPkcvRk3gmqL0fySaD42CRuuPHVEeRECChwF3JWoLy4JetGUcwaOaOZLanqR4PUE42dm6Ur6+J1ZcxMkMAnaqJcdbUd3pTn94Zt56qObvi66Izb/nYzaq+04KOo960tPwWxsz4wGoU8EUTipceJGoZRVAgrL1O3CNEesIOsyCqWPvTwbxA4ykJDaHz4NbFxShr0I5Ov3etdN59bJylniHZOFFE3AZgi+AWR7hlBCUEv5qsnKxk32EBqdkNNDQGhI/12t+STlP1Xl2XOrNMK+8hr5WXRiXSFInhi9gBPx3cu4rsCekv7CmPxtUvdL3uPJGazMz72EL7ZYjS1/qjPmS2w792+7Sc5MdJJMVctLuKroTJh+5ALuHPlV1cKxPnr/KrDet0M/dylIb11M7D+8xEehEPrLM3moiiXxteWC9famhi00oIcLqLuGzC59Rcmtw4eJTz6y+66hF1E1/Voru7gintIFjtCxY1sqPbGGbtUr3YDYzdNiXMDrEfaJXzaSW+m+ctgJR1XUEZiq0yHv0G+EV7lG7fDn7v1cE5T6WC6OnRLe44z6m/9x775F2m2WV8/hr63TbdsfHBJ9eILz2zZKvy95aaleC0gk10UTPTg+oM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
