travis:
  secure:
    BINSTAR_TOKEN: RH7SMsrdG5exSzBFZxUlWZllInsdTE5ofN5f9HhSozF3LYyp1jaMtCjGPiAxlPJfyYaRNtzZzdcdcgLp8sQn8l/d+/OsgDi8VPCqoYtSgyE9aP5kBIsFJF2sPmGOTG046fYidc2jZawVzqL3ifYKxGzdug9lgLCEIOUVnif+2NGSuUcXzaI8LVvdTVZVzUB56g+pK+cS2KSVgtU+McmcJM0Z/xOz5lcBEQIS1Tx/Qr3rc1MWDSdwzTEgoWxQJhSI8rgsEhEQOtjSa6Y+weUzZvMrwr6jvFojHCpk52Ig5rJtdItsCerY4eXsgNp9Y+JsEwQQRNUkDOxGSZgCLxl4lEcyYIO41x/0bM2+v74H1B1Z8CsnfbnS4TKfSDe9x6+Ce5K46S1jVawcucq8fqB723WxVp7Y44L7uhU8vxIJHppV3jDTt1xD4WvEhvB9gDlozWKA8iZcfwFO/KNeoOdaE92ImgJ0XewVikdXalj8LUlxGW9GpQmhyqaQ7Y5UA7zSYABGbS+fEpXPaPMFsHVStk0Qj1iiM1sNf9TQ+tg1Czh4aEbm8ZSNqkhLsXL0ISgwX3FfRl+0yH0RLIOcCOftVfit/Q2thnGDa1SqZNSFy5h7/ZDf3HB9rHnrNrigKAkzHkjDR1ELFv4xe8aLEN9O8bwjGf34yKkQNVnO2rljtII=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
